location /desktop/{instance_id}/vnc/ {
    proxy_pass         https://{upstream_ip}:6901/;
    proxy_ssl_verify   off;
    proxy_set_header   Authorization      "Basic {auth_header}";
    proxy_set_header   Host               $host;
    proxy_set_header   X-Real-IP          $remote_addr;
    proxy_set_header   X-Forwarded-For    $proxy_add_x_forwarded_for;
}

location /desktop/{instance_id}/vnc/websockify {
    proxy_pass         https://{upstream_ip}:6901/websockify;
    proxy_ssl_verify   off;
    proxy_http_version 1.1;
    proxy_set_header   Upgrade            $http_upgrade;
    proxy_set_header   Connection         "upgrade";
    proxy_set_header   Host               $host;
    proxy_cache_bypass $http_upgrade;
    proxy_read_timeout 86400s;
    proxy_buffering    off;
    proxy_set_header   Authorization      "Basic {auth_header}";
}

location /desktop/{instance_id}/audio/ {
    proxy_pass         https://{upstream_ip}:4901/;
    proxy_ssl_verify   off;
    proxy_http_version 1.1;
    proxy_set_header   Upgrade            $http_upgrade;
    proxy_set_header   Connection         "upgrade";
    proxy_set_header   Host               $host;
    proxy_cache_bypass $http_upgrade;
    proxy_read_timeout 86400s;
    proxy_buffering    off;
    proxy_set_header   Authorization      "Basic {auth_header}";
}
