location /desktop/{instance_id}/vnc/ {
	auth_request /tide_connect;
	auth_request_set $cookie_token $upstream_http_set_cookie;

	proxy_pass http://{guac_host}:{guac_port}/;
}

location /desktop/{instance_id}/vnc/websockify {
	auth_request /tide_connect;
	auth_request_set $cookie_token $upstream_http_set_cookie;

	proxy_pass http://{guac_host}:{guac_port}/websockify/;
	proxy_http_version 1.1;
	proxy_set_header Upgrade $http_upgrade;
	proxy_set_header Connection 'upgrade';
	proxy_set_header Host $host;
	proxy_cache_bypass $http_upgrade;

	proxy_read_timeout 86400s;
	proxy_buffering off;
}
